/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pms.ui;

import com.pms.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author MSI
 */
public class TrangChu extends javax.swing.JFrame {

    Boolean truongPhong;
    String maNV, tenNV, urlAnh;
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.WHITE);
        SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
        new Timer(5, (ActionEvent e) -> {
            lblDongho.setText(format.format(new Date()));
        }).start();
        this.setIconImage(XImage.getAppIcon());
    }
    
    public void get_Data_From_DifFrame(Boolean tp, String manv, String tennv, String urlanh){
        truongPhong = tp;
        maNV = manv;
        tenNV = tennv;
        urlAnh = urlanh;
        lblChucVuNhanVien.setText(tp==true?"Trưởng phòng":"Nhân viên");
        lblTenNhanVien.setText(tennv);
        int newHeight = (lblAnhNhanVien.getWidth() * new ImageIcon(urlanh).getImage().getHeight(null)) / new ImageIcon(urlanh).getImage().getWidth(null);
        Image img = new ImageIcon(urlanh).getImage().getScaledInstance(lblAnhNhanVien.getWidth(), newHeight, Image.SCALE_SMOOTH);
        lblAnhNhanVien.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAnhNhanVien = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnDanhSach = new javax.swing.JButton();
        btnXuatHang = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblDongho = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblChucVuNhanVien = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        btnLichSuXuatNhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mnbMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnHeThong = new javax.swing.JMenu();
        mniDangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniDoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnQuanLy = new javax.swing.JMenu();
        mniDanhSachSanPham = new javax.swing.JMenuItem();
        mniXuatHang = new javax.swing.JMenuItem();
        mniNhapHang = new javax.swing.JMenuItem();
        mnBaoCao = new javax.swing.JMenu();
        mniLichSuXuatNhap = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniThongKeHangThang = new javax.swing.JMenuItem();
        mnTroGiup = new javax.swing.JMenu();
        mniHuongDanSuDung = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniVeChungToi = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setPreferredSize(new java.awt.Dimension(1927, 976));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setForeground(new java.awt.Color(151, 204, 253));

        lblAnhNhanVien.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblAnhNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblAnhNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnhNhanVien.setText("<Hình ảnh>");
        lblAnhNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAnhNhanVien.setIconTextGap(5);
        lblAnhNhanVien.setVerifyInputWhenFocusTarget(false);

        btnDangXuat.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(0, 51, 102));
        btnDangXuat.setBorder(null);
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setLabel("Đăng xuất");
        btnDangXuat.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnDanhSach.setBackground(new java.awt.Color(231, 245, 255));
        btnDanhSach.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnDanhSach.setForeground(new java.awt.Color(0, 51, 102));
        btnDanhSach.setText("Danh sách hàng hóa");
        btnDanhSach.setBorder(null);
        btnDanhSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDanhSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDanhSach.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnDanhSach.setOpaque(true);
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnXuatHang.setBackground(new java.awt.Color(231, 245, 255));
        btnXuatHang.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnXuatHang.setForeground(new java.awt.Color(0, 51, 102));
        btnXuatHang.setText("Xuất hàng");
        btnXuatHang.setBorder(null);
        btnXuatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuatHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXuatHang.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnXuatHang.setOpaque(true);
        btnXuatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHangActionPerformed(evt);
            }
        });

        btnNhapHang.setBackground(new java.awt.Color(231, 245, 255));
        btnNhapHang.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnNhapHang.setForeground(new java.awt.Color(0, 51, 102));
        btnNhapHang.setText("Nhập hàng");
        btnNhapHang.setBorder(null);
        btnNhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapHang.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnNhapHang.setOpaque(true);
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(231, 245, 255));
        btnNhanVien.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(0, 51, 102));
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setBorder(null);
        btnNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setIconTextGap(5);
        btnNhanVien.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnNhanVien.setOpaque(true);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("v01.30.06.24");

        lblDongho.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblDongho.setForeground(new java.awt.Color(255, 255, 255));
        lblDongho.setText("jLabel1");

        lblTenNhanVien.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblTenNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNhanVien.setText("Dương Quốc Hiếu");
        lblTenNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTenNhanVien.setIconTextGap(5);
        lblTenNhanVien.setVerifyInputWhenFocusTarget(false);

        lblChucVuNhanVien.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lblChucVuNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVuNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVuNhanVien.setText("Trưởng phòng");
        lblChucVuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblChucVuNhanVien.setIconTextGap(5);
        lblChucVuNhanVien.setVerifyInputWhenFocusTarget(false);

        btnThongKe.setBackground(new java.awt.Color(231, 245, 255));
        btnThongKe.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(0, 51, 102));
        btnThongKe.setText("Thống kê hàng tháng");
        btnThongKe.setBorder(null);
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnThongKe.setOpaque(true);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnLichSuXuatNhap.setBackground(new java.awt.Color(231, 245, 255));
        btnLichSuXuatNhap.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnLichSuXuatNhap.setForeground(new java.awt.Color(0, 51, 102));
        btnLichSuXuatNhap.setText("Lịch sử xuất nhập hàng");
        btnLichSuXuatNhap.setBorder(null);
        btnLichSuXuatNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLichSuXuatNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLichSuXuatNhap.setIconTextGap(5);
        btnLichSuXuatNhap.setMargin(new java.awt.Insets(0, 20, 0, 0));
        btnLichSuXuatNhap.setOpaque(true);
        btnLichSuXuatNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuXuatNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblDongho, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123))
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLichSuXuatNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXuatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblChucVuNhanVien)
                            .addComponent(lblAnhNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenNhanVien))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAnhNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVuNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDanhSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXuatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLichSuXuatNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lblDongho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pms/icon/poly_1.png"))); // NOI18N

        mnbMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnbMenuBar.setOpaque(true);

        jMenu1.setForeground(new java.awt.Color(0, 51, 153));
        jMenu1.setText("     ProBoox     ");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        mnbMenuBar.add(jMenu1);

        mnHeThong.setText("Hệ thống");
        mnHeThong.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        mniDangXuat.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnHeThong.add(mniDangXuat);
        mnHeThong.add(jSeparator1);

        mniDoiMatKhau.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniDoiMatKhau.setText("Đổi mật khẩu");
        mniDoiMatKhau.setIconTextGap(4);
        mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKhauActionPerformed(evt);
            }
        });
        mnHeThong.add(mniDoiMatKhau);
        mnHeThong.add(jSeparator2);

        mniExit.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnHeThong.add(mniExit);

        mnbMenuBar.add(mnHeThong);

        mnQuanLy.setText("Quản lý");
        mnQuanLy.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        mniDanhSachSanPham.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniDanhSachSanPham.setText("Danh sách sản phẩm hiện có");
        mniDanhSachSanPham.setIconTextGap(15);
        mniDanhSachSanPham.setMargin(new java.awt.Insets(5, 6, 5, 6));
        mniDanhSachSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDanhSachSanPhamActionPerformed(evt);
            }
        });
        mnQuanLy.add(mniDanhSachSanPham);

        mniXuatHang.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniXuatHang.setText("Xuất hàng");
        mniXuatHang.setIconTextGap(15);
        mniXuatHang.setMargin(new java.awt.Insets(5, 6, 5, 6));
        mniXuatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniXuatHangActionPerformed(evt);
            }
        });
        mnQuanLy.add(mniXuatHang);

        mniNhapHang.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniNhapHang.setText("Nhập hàng");
        mniNhapHang.setIconTextGap(15);
        mniNhapHang.setMargin(new java.awt.Insets(5, 6, 5, 6));
        mniNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhapHangActionPerformed(evt);
            }
        });
        mnQuanLy.add(mniNhapHang);

        mnbMenuBar.add(mnQuanLy);

        mnBaoCao.setText("Báo cáo");
        mnBaoCao.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        mniLichSuXuatNhap.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniLichSuXuatNhap.setText("Lịch sử xuất nhập kho");
        mniLichSuXuatNhap.setIconTextGap(15);
        mniLichSuXuatNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLichSuXuatNhapActionPerformed(evt);
            }
        });
        mnBaoCao.add(mniLichSuXuatNhap);
        mnBaoCao.add(jSeparator3);

        mniThongKeHangThang.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniThongKeHangThang.setText("Thống kê hàng tháng");
        mniThongKeHangThang.setIconTextGap(15);
        mniThongKeHangThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniThongKeHangThangActionPerformed(evt);
            }
        });
        mnBaoCao.add(mniThongKeHangThang);

        mnbMenuBar.add(mnBaoCao);

        mnTroGiup.setText("Trợ giúp");
        mnTroGiup.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        mniHuongDanSuDung.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniHuongDanSuDung.setText("Hướng dẫn sử dụng");
        mnTroGiup.add(mniHuongDanSuDung);
        mnTroGiup.add(jSeparator4);

        mniVeChungToi.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mniVeChungToi.setText("Về chúng tôi");
        mniVeChungToi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVeChungToiActionPerformed(evt);
            }
        });
        mnTroGiup.add(mniVeChungToi);

        mnbMenuBar.add(mnTroGiup);

        setJMenuBar(mnbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1566, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        dispose();
        DangNhap dangNhapJFrame = new DangNhap();
        dangNhapJFrame.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        dispose();
        QuanLyDanhSachHang danhSachHangJFrame = new QuanLyDanhSachHang();
        danhSachHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        danhSachHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnXuatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHangActionPerformed
        dispose();
        XuatHang xuatHangJFrame = new XuatHang();
        xuatHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        xuatHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnXuatHangActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        dispose();
        NhapHang nhapHangJFrame = new NhapHang();
        nhapHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        nhapHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if(truongPhong==false){
            JOptionPane.showMessageDialog(this, "Không đủ quyền truy cập!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dispose();
            Nhanvien nhanvienJFrame = new Nhanvien();
            nhanvienJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
            nhanvienJFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        dispose();
        ThongKeThang thongKeJFrame = new ThongKeThang();
        thongKeJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        thongKeJFrame.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnLichSuXuatNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuXuatNhapActionPerformed
        if(truongPhong==false){
            JOptionPane.showMessageDialog(this, "Không đủ quyền truy cập!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dispose();
            LichSuXuatNhap lichSuXuatNhapJFrame = new LichSuXuatNhap();
            lichSuXuatNhapJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
            lichSuXuatNhapJFrame.setVisible(true);
        }
    }//GEN-LAST:event_btnLichSuXuatNhapActionPerformed

    private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
        dispose();
        DoiMatkhau doiMatkhauJFrame = new DoiMatkhau();
        doiMatkhauJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        doiMatkhauJFrame.setVisible(true);
    }//GEN-LAST:event_mniDoiMatKhauActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        dispose();
        DangNhap dangNhapJFrame = new DangNhap();
        dangNhapJFrame.setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniDanhSachSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDanhSachSanPhamActionPerformed
        dispose();
        QuanLyDanhSachHang danhSachHangJFrame = new QuanLyDanhSachHang();
        danhSachHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        danhSachHangJFrame.setVisible(true);
    }//GEN-LAST:event_mniDanhSachSanPhamActionPerformed

    private void mniXuatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniXuatHangActionPerformed
        dispose();
        XuatHang xuatHangJFrame = new XuatHang();
        xuatHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        xuatHangJFrame.setVisible(true);
    }//GEN-LAST:event_mniXuatHangActionPerformed

    private void mniNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhapHangActionPerformed
        dispose();
        NhapHang nhapHangJFrame = new NhapHang();
        nhapHangJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        nhapHangJFrame.setVisible(true);
    }//GEN-LAST:event_mniNhapHangActionPerformed

    private void mniLichSuXuatNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLichSuXuatNhapActionPerformed
        if(truongPhong==false){
            JOptionPane.showMessageDialog(this, "Không đủ quyền truy cập!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dispose();
            LichSuXuatNhap lichSuXuatNhapJFrame = new LichSuXuatNhap();
            lichSuXuatNhapJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
            lichSuXuatNhapJFrame.setVisible(true);
        }
    }//GEN-LAST:event_mniLichSuXuatNhapActionPerformed

    private void mniThongKeHangThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongKeHangThangActionPerformed
        dispose();
        ThongKeThang thongKeJFrame = new ThongKeThang();
        thongKeJFrame.get_Data_From_DifFrame(truongPhong, maNV, tenNV, urlAnh);
        thongKeJFrame.setVisible(true);
    }//GEN-LAST:event_mniThongKeHangThangActionPerformed

    private void mniVeChungToiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVeChungToiActionPerformed
        AboutUs aboutUsJDialog = new AboutUs(this, true);
        aboutUsJDialog.setVisible(true);
    }//GEN-LAST:event_mniVeChungToiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnLichSuXuatNhap;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnXuatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblAnhNhanVien;
    private javax.swing.JLabel lblChucVuNhanVien;
    private javax.swing.JLabel lblDongho;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JMenu mnBaoCao;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenu mnTroGiup;
    private javax.swing.JMenuBar mnbMenuBar;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDanhSachSanPham;
    private javax.swing.JMenuItem mniDoiMatKhau;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniHuongDanSuDung;
    private javax.swing.JMenuItem mniLichSuXuatNhap;
    private javax.swing.JMenuItem mniNhapHang;
    private javax.swing.JMenuItem mniThongKeHangThang;
    private javax.swing.JMenuItem mniVeChungToi;
    private javax.swing.JMenuItem mniXuatHang;
    // End of variables declaration//GEN-END:variables
}
